### ISSUE TITLE
osc needs to use token auth (or something other than certs)

### ISSUE THREAD

**Issue by brenton** [openshift/training#32] opened 2015-03-04 21:37 UTC
I haven't seen how we're configuring auth for the `joe` user.  To continue testing beta2 and work around the problem I browsed to https://ose3-master.example.com:8443/oauth/token/request

Once I had the token I added the following to my `.kubeconfig`:

```
- name: joe
  user:
    token: <token from browser request>
```

**Comment by thoraxe** [comment] 2015-03-04 21:57
Yes, I encountered this, too. The issue is that we were doing nothing at the CLI for auth because nothing was required previously.

If there is no way to supply the password with the CLI command (htpasswd), then we will have to write instructions for how to auth.

**Comment by brenton** [comment] 2015-03-05 12:52
Eventually we'll have an 'osc login' command but that didn't make it in to beta2.  That's the command that would allow you to get a token via basic auth and likely autoupdate your .kubeconfig.  For now we don't have that so I'll write up some instructions on manually fetching a token.

**Comment by brenton** [comment] 2015-03-05 14:58
Jordan showed me this oneliner we could use to get the token for beta2:

```
curl -s -k "https://`hostname`:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client" -u joe:redhat -v 2>&1 | grep -oP "access_token=\K[^&]*"
```

We'll probably want to wrap that in a script that also updates the related $KUBECONFIG section for the joe user.

**Comment by brenton** [comment] 2015-03-05 16:36
@thoraxe, I'm correct in thinking that we expect people to run osc from the master for beta2, right?

**Comment by thoraxe** [comment] 2015-03-05 16:45
Yes, there are now two paradigms:

1) root user who is doing admin functions (creating projects)

2) non-root user (joe/alice) who is using osc/openshift to create apps and stuff.

**Comment by thoraxe** [comment] 2015-03-05 18:27
We can actually use ex login, so no curl is necessary.

**Comment by thoraxe** [comment] 2015-03-05 18:27
See my latest push for the beginnings of some examples using `openshift ex login`. I will actually go ahead and close this since it seems to be working.

**Closed as completed by thoraxe** 2015-03-05 18:27 UTC

**Comment by brenton** [comment] 2015-03-05 18:30
AWESOME.  I didn't know that code was in yet.

**Comment by brenton** [comment] 2015-03-05 18:49
You  might hit some bugs with `openshift ex login`.  As best I can tell in the code I'm running it only creates a `.kubeconfig` in the current working directory.  It won't update whatever $KUBECONFIG is pointing to unless it happens to match.

It also looked like it was setting up the cluster in the kubeconfig incorrectly (or partly, rather).  By this I mean it didn't have any of the server's CA info in there so I had to manually switch contexts to one what was working.  It did allow me to correctly fetch a token though which is what really matter.  Let me know if you need anything else with this.  For now I'm going to look into the build-logs thing.

**Comment by brenton** [comment] 2015-03-05 18:53
ahh, looking at IRC now I see the `--certificate-authority` flag.  I guess we're all set.

**Comment by thoraxe** [comment] 2015-03-05 22:10
I only use ex login the first time.

After that I am using set-context, which does operate on $KUBECONFIG
